catalogMode: prefer
cleanupUnusedCatalogs: true
ignoreWorkspaceRootCheck: true
linkWorkspacePackages: true
shamefullyHoist: true
shellEmulator: true
strictPeerDependencies: false
trustPolicy: no-downgrade
packages:
  - apps/*
  - packages/*
overrides:
  chokidar: ^5.0.0
  semver: ^7.7.4
catalog:
  '@antfu/eslint-config': ^7.6.1
  '@commitlint/cli': ^20.4.2
  '@commitlint/config-conventional': ^20.4.2
  '@iconify-json/ph': ^1.2.2
  '@nuxt/image': ^2.0.0
  '@pinia/nuxt': ^0.11.3
  '@unocss/eslint-plugin': ^66.6.3
  '@unocss/nuxt': ^66.6.2
  eslint: ^10.0.2
  eslint-plugin-format: ^2.0.1
  esno: ^4.8.0
  lint-staged: ^16.3.1
  nuxt: ^4.3.1
  simple-git-hooks: ^2.13.1
  turbo: ^2.8.12
  typescript: ^5.9.3
  unbuild: ^3.6.1
  vite: ^7.3.1
  vitest: ^4.0.18
  vue: ^3.5.29
  vue-tsc: ^3.2.5
onlyBuiltDependencies:
  - simple-git-hooks
